### ISSUE TITLE
Display search message in chart title

### ISSUE THREAD

**Issue by JasonFritsche** [JasonFritsche/word-traverse#6]
Currently the search message (ex. "You searched for nouns that are described by amazing") is shown at the bottom of the search panel/form. This message should be rendered as the chart title and the verbiage should be changed "you searched for" to "showing results for".

**Comment by krishan-here** [comment]
hey @JasonFritsche this is an awesome project!
I am interested to work on this. Could you please assign this to me.

**Comment by JasonFritsche** [comment]
@krishan-here thanks for taking an interest in the project. This issue is all yours.
